# Generated by Django 2.0 on 2020-02-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sender', max_length=80)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('cont_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
